<a href="https://colab.research.google.com/github/kanishka55/import_data/blob/main/abuse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv('/content/drive/MyDrive/colab/OS/Datasets/labeled_data.csv')

In [4]:
dataset

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0      !!! RT @mayasolovely: As a woman you shouldn't...  
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...  
...                                                  ...  
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...  
24779  you've gone and broke the wrong heart baby, an...  
24780  young buck wanna eat!!.. dat nigguh like I ain...  
24781              youu got wild bitches tellin you lies  
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...  

[24783 rows x 7 columns]

In [5]:
dataset['tweet']

0        !!! RT @mayasolovely: As a woman you shouldn't...
1        !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2        !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3        !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4        !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
                               ...                        
24778    you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779    you've gone and broke the wrong heart baby, an...
24780    young buck wanna eat!!.. dat nigguh like I ain...
24781                youu got wild bitches tellin you lies
24782    ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...
Name: tweet, Length: 24783, dtype: object

In [6]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [7]:
#defining the function to remove punctuation
def remove_punctuation(text):
    punctuationfree=''.join([i for i in text if i not in string.punctuation])
    return punctuationfree

In [8]:
dataset['without_pun'] = dataset['tweet'].apply(lambda x: remove_punctuation(x))

In [9]:
dataset['without_pun']

0         RT mayasolovely As a woman you shouldnt compl...
1         RT mleew17 boy dats coldtyga dwn bad for cuff...
2         RT UrKindOfBrand Dawg RT 80sbaby4life You eve...
3           RT CGAnderson vivabased she look like a tranny
4         RT ShenikaRoberts The shit you hear about me ...
                               ...                        
24778    yous a muthafin lie 8220LifeAsKing 20Pearls co...
24779    youve gone and broke the wrong heart baby and ...
24780    young buck wanna eat dat nigguh like I aint fu...
24781                youu got wild bitches tellin you lies
24782    Ruffled  Ntac Eileen Dahlia  Beautiful color c...
Name: without_pun, Length: 24783, dtype: object

In [10]:
import re


In [11]:
def clean_unwant(text):
    text = re.sub(r'(RT[^\n]+\n)', '', text)
    return text

In [ ]:
##dataset['unwant_cleaned'] = dataset['without_pun'].apply(lambda x: clean_unwant(x))

In [ ]:
##dataset['unwant_cleaned']

0         RT mayasolovely As a woman you shouldnt compl...
1         RT mleew17 boy dats coldtyga dwn bad for cuff...
2         RT UrKindOfBrand Dawg RT 80sbaby4life You eve...
3           RT CGAnderson vivabased she look like a tranny
4         RT ShenikaRoberts The shit you hear about me ...
                               ...                        
24778    yous a muthafin lie 8220LifeAsKing 20Pearls co...
24779    youve gone and broke the wrong heart baby and ...
24780    young buck wanna eat dat nigguh like I aint fu...
24781                youu got wild bitches tellin you lies
24782    Ruffled  Ntac Eileen Dahlia  Beautiful color c...
Name: unwant_cleaned, Length: 24783, dtype: object

In [12]:
remove_words = ['RT']

In [13]:
pat = r'\b(?:{})\b'.format('|'.join(remove_words))

In [14]:
pat

'\\b(?:RT)\\b'

In [15]:
dataset['unwant_cleaned'] = dataset['without_pun'].str.replace(pat, '')


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.


In [16]:
dataset['unwant_cleaned']

0          mayasolovely As a woman you shouldnt complai...
1          mleew17 boy dats coldtyga dwn bad for cuffin...
2          UrKindOfBrand Dawg  80sbaby4life You ever fu...
3              CGAnderson vivabased she look like a tranny
4          ShenikaRoberts The shit you hear about me mi...
                               ...                        
24778    yous a muthafin lie 8220LifeAsKing 20Pearls co...
24779    youve gone and broke the wrong heart baby and ...
24780    young buck wanna eat dat nigguh like I aint fu...
24781                youu got wild bitches tellin you lies
24782    Ruffled  Ntac Eileen Dahlia  Beautiful color c...
Name: unwant_cleaned, Length: 24783, dtype: object

In [17]:
#importing nlp library
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [18]:
#Stop words present in the library
stopwords = nltk.corpus.stopwords.words('english')

In [19]:
##The function for remove stopwords in dataset
def remove_stopwords(text):
    output= ' '.join([word for word in text.split() if word not in stopwords])
    return output

In [20]:
#applying the stopword function
dataset['no_stopwords']= dataset['unwant_cleaned'].apply(lambda x:remove_stopwords(x))

In [21]:
dataset['no_stopwords']

0        mayasolovely As woman shouldnt complain cleani...
1        mleew17 boy dats coldtyga dwn bad cuffin dat h...
2        UrKindOfBrand Dawg 80sbaby4life You ever fuck ...
3                    CGAnderson vivabased look like tranny
4        ShenikaRoberts The shit hear might true might ...
                               ...                        
24778    yous muthafin lie 8220LifeAsKing 20Pearls core...
24779    youve gone broke wrong heart baby drove rednec...
24780    young buck wanna eat dat nigguh like I aint fu...
24781                    youu got wild bitches tellin lies
24782    Ruffled Ntac Eileen Dahlia Beautiful color com...
Name: no_stopwords, Length: 24783, dtype: object

In [22]:
dataset['lower']= dataset['no_stopwords'].apply(lambda x: x.lower())

In [23]:
dataset['lower']

0        mayasolovely as woman shouldnt complain cleani...
1        mleew17 boy dats coldtyga dwn bad cuffin dat h...
2        urkindofbrand dawg 80sbaby4life you ever fuck ...
3                    cganderson vivabased look like tranny
4        shenikaroberts the shit hear might true might ...
                               ...                        
24778    yous muthafin lie 8220lifeasking 20pearls core...
24779    youve gone broke wrong heart baby drove rednec...
24780    young buck wanna eat dat nigguh like i aint fu...
24781                    youu got wild bitches tellin lies
24782    ruffled ntac eileen dahlia beautiful color com...
Name: lower, Length: 24783, dtype: object

In [24]:
#defining function for tokenization
import re
def tokenization(text):
    tokens = re.findall('[\w]+',text)
    return tokens
#applying function to the column
dataset['tokenied']= dataset['lower'].apply(lambda x: tokenization(x))

In [25]:
dataset['tokenied']

0        [mayasolovely, as, woman, shouldnt, complain, ...
1        [mleew17, boy, dats, coldtyga, dwn, bad, cuffi...
2        [urkindofbrand, dawg, 80sbaby4life, you, ever,...
3              [cganderson, vivabased, look, like, tranny]
4        [shenikaroberts, the, shit, hear, might, true,...
                               ...                        
24778    [yous, muthafin, lie, 8220lifeasking, 20pearls...
24779    [youve, gone, broke, wrong, heart, baby, drove...
24780    [young, buck, wanna, eat, dat, nigguh, like, i...
24781             [youu, got, wild, bitches, tellin, lies]
24782    [ruffled, ntac, eileen, dahlia, beautiful, col...
Name: tokenied, Length: 24783, dtype: object

In [26]:
#importing the Stemming function from nltk library
from nltk.stem.porter import PorterStemmer
#defining the object for stemming
porter_stemmer = PorterStemmer()

In [27]:
#defining a function for stemming
def stemming(text):
  stem_text = [porter_stemmer.stem(word) for word in text]
  return stem_text

In [28]:
dataset['stemmed']=dataset['tokenied'].apply(lambda x: stemming(x))

In [29]:
dataset['stemmed']

0        [mayasolov, as, woman, shouldnt, complain, cle...
1        [mleew17, boy, dat, coldtyga, dwn, bad, cuffin...
2        [urkindofbrand, dawg, 80sbaby4lif, you, ever, ...
3                [cganderson, vivabas, look, like, tranni]
4        [shenikarobert, the, shit, hear, might, true, ...
                               ...                        
24778    [you, muthafin, lie, 8220lifeask, 20pearl, cor...
24779    [youv, gone, broke, wrong, heart, babi, drove,...
24780    [young, buck, wanna, eat, dat, nigguh, like, i...
24781                [youu, got, wild, bitch, tellin, lie]
24782    [ruffl, ntac, eileen, dahlia, beauti, color, c...
Name: stemmed, Length: 24783, dtype: object

In [30]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [31]:
from nltk.stem import WordNetLemmatizer
#defining the object for Lemmatization
wordnet_lemmatizer = WordNetLemmatizer()

In [32]:
#defining the function for lemmatization
def lemmatizer(text):
  lemm_text = [wordnet_lemmatizer.lemmatize(word) for word in text]
  return lemm_text

In [33]:
dataset['lemmatized']=dataset['tokenied'].apply(lambda x:lemmatizer(x))

In [34]:
dataset['lemmatized']

0        [mayasolovely, a, woman, shouldnt, complain, c...
1        [mleew17, boy, dat, coldtyga, dwn, bad, cuffin...
2        [urkindofbrand, dawg, 80sbaby4life, you, ever,...
3              [cganderson, vivabased, look, like, tranny]
4        [shenikaroberts, the, shit, hear, might, true,...
                               ...                        
24778    [yous, muthafin, lie, 8220lifeasking, 20pearls...
24779    [youve, gone, broke, wrong, heart, baby, drove...
24780    [young, buck, wanna, eat, dat, nigguh, like, i...
24781                [youu, got, wild, bitch, tellin, lie]
24782    [ruffled, ntac, eileen, dahlia, beautiful, col...
Name: lemmatized, Length: 24783, dtype: object

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = CountVectorizer(min_df=0.3, max_df=0.7,)
X = vectorizer.fit_transform(dataset['lower']).toarray()

In [36]:
X

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [37]:
from tkinter import YView
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfconverter = TfidfVectorizer(min_df=0.3, max_df=0.7)
Y = tfidfconverter.fit_transform(dataset['lower']).toarray()

In [38]:
Y

array([[0.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [39]:
from sklearn.cluster import KMeans
import numpy as np

In [40]:
km=KMeans(n_clusters=2,n_init=25,random_state=23)
km.fit(X)
y_cluster=km.predict(X)
y_cluster

array([1, 1, 0, ..., 1, 1, 1], dtype=int32)

In [41]:
#Count Cluster
from collections import Counter
cnt=Counter(y_cluster)
cnt

Counter({1: 17093, 0: 7690})