<a href="https://colab.research.google.com/github/kanishka55/import_data/blob/main/abusive_text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [63]:
!wget https://github.com/mohit3011/AbuseAnalyzer/blob/main/AbuseAnalyzer_Dataset.tsv?raw=true

--2022-09-16 04:44:52--  https://github.com/mohit3011/AbuseAnalyzer/blob/main/AbuseAnalyzer_Dataset.tsv?raw=true
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/mohit3011/AbuseAnalyzer/raw/main/AbuseAnalyzer_Dataset.tsv [following]
--2022-09-16 04:44:52--  https://github.com/mohit3011/AbuseAnalyzer/raw/main/AbuseAnalyzer_Dataset.tsv
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/mohit3011/AbuseAnalyzer/main/AbuseAnalyzer_Dataset.tsv [following]
--2022-09-16 04:44:52--  https://raw.githubusercontent.com/mohit3011/AbuseAnalyzer/main/AbuseAnalyzer_Dataset.tsv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|18

In [64]:
import pandas as pd
import re

In [65]:
df = pd.read_csv('/content/drive/MyDrive/colab/OS/Datasets/AbuseAnalyzer_Dataset.tsv?raw=true',sep='\t')

In [66]:
df

Post Text Emoji  Hate/Non-Hate  \
0                     ALS AT RED BLACKS LIVE RIGHT NOW!   NaN              1   
1     Rigged election will cause civil war just my o...   NaN              1   
2     I fucking love it ! Sorry I can only offer him...   NaN              2   
3     What a steaming load of shit!  https://help.tw...   NaN              2   
4     Until he does rule it out. The man fucking fli...   NaN              2   
...                                                 ...   ...            ...   
7596  I am calling for everyone to surround Mikes re...   NaN              1   
7597  LMFAO he was going hit the chic tell realized ...   NaN              2   
7598                 Amazing how Ann got so much wrong.   NaN              2   
7599  lol little Anthony drew attention to himself.....     😈              1   
7600  Bumper Sticker FREE TOMMY https://www.zazzle.c...   NaN              1   

     Target of Hate  Class of Hate  
0               NaN            NaN  
1               NaN            NaN  
2               1-3            1.0  
3                 2            1.0  
4               1-3            1.0  
...             ...            ...  
7596            NaN            NaN  
7597              2            2.0  
7598            1-3            1.0  
7599            NaN            NaN  
7600            NaN            NaN  

[7601 rows x 5 columns]

In [67]:
df['Post Text']

0                       ALS AT RED BLACKS LIVE RIGHT NOW!
1       Rigged election will cause civil war just my o...
2       I fucking love it ! Sorry I can only offer him...
3       What a steaming load of shit!  https://help.tw...
4       Until he does rule it out. The man fucking fli...
                              ...                        
7596    I am calling for everyone to surround Mikes re...
7597    LMFAO he was going hit the chic tell realized ...
7598                   Amazing how Ann got so much wrong.
7599    lol little Anthony drew attention to himself.....
7600    Bumper Sticker FREE TOMMY https://www.zazzle.c...
Name: Post Text, Length: 7601, dtype: object

In [68]:
def remove_URL(text):
    """Remove URLs from a text string"""
    return re.sub(r"http\S+", "", text) 

In [69]:
df['no_url']= df['Post Text'].apply(lambda x:remove_URL(x))

In [70]:
df['no_url']

0                       ALS AT RED BLACKS LIVE RIGHT NOW!
1       Rigged election will cause civil war just my o...
2       I fucking love it ! Sorry I can only offer him...
3                         What a steaming load of shit!  
4       Until he does rule it out. The man fucking fli...
                              ...                        
7596    I am calling for everyone to surround Mikes re...
7597    LMFAO he was going hit the chic tell realized ...
7598                   Amazing how Ann got so much wrong.
7599    lol little Anthony drew attention to himself.....
7600                           Bumper Sticker FREE TOMMY 
Name: no_url, Length: 7601, dtype: object

In [71]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [72]:
#defining the function to remove punctuation
def remove_punctuation(text):
    punctuationfree=''.join([i for i in text if i not in string.punctuation])
    return punctuationfree

In [73]:
df['nopuc_text'] = df['no_url'].apply(lambda x: remove_punctuation(x))

In [74]:
df['nopuc_text']

0                        ALS AT RED BLACKS LIVE RIGHT NOW
1       Rigged election will cause civil war just my o...
2       I fucking love it  Sorry I can only offer him ...
3                          What a steaming load of shit  
4       Until he does rule it out The man fucking flip...
                              ...                        
7596    I am calling for everyone to surround Mikes re...
7597    LMFAO he was going hit the chic tell realized ...
7598                    Amazing how Ann got so much wrong
7599    lol little Anthony drew attention to himselfmi...
7600                           Bumper Sticker FREE TOMMY 
Name: nopuc_text, Length: 7601, dtype: object

In [75]:
import re

In [85]:
def clean_text(text):
  text = text.lower()
  text = text.strip()  ##to remove the whitespace from the beginning and at the end of the string
  text = re.sub(r'(\d+)', ' ', text)
  text = re.sub(r'(\s+)', ' ', text)
  return text

In [86]:
df['clean'] = df['nopuc_text'].apply(lambda x:clean_text(x))

In [87]:
df['clean']

0                        als at red blacks live right now
1       rigged election will cause civil war just my o...
2       i fucking love it sorry i can only offer him a...
3                            what a steaming load of shit
4       until he does rule it out the man fucking flip...
                              ...                        
7596    i am calling for everyone to surround mikes re...
7597    lmfao he was going hit the chic tell realized ...
7598                    amazing how ann got so much wrong
7599    lol little anthony drew attention to himselfmi...
7600                            bumper sticker free tommy
Name: clean, Length: 7601, dtype: object

In [88]:
#importing nlp library
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [89]:
#Stop words present in the library
stopwords = nltk.corpus.stopwords.words('english')

In [90]:
##The function for remove stopwords in dataset
def remove_stopwords(text):
    output= ' '.join([word for word in text.split() if word not in stopwords])
    return output

In [93]:
df['no_stopword']= df['clean'].apply(lambda x:remove_stopwords(x))

In [94]:
df['no_stopword']

0                               als red blacks live right
1                 rigged election cause civil war opinion
2              fucking love sorry offer job union laborer
3                                      steaming load shit
4                  rule man fucking flip flops everything
                              ...                        
7596    calling everyone surround mikes refrigerator f...
7597    lmfao going hit chic tell realized chic dont w...
7598                           amazing ann got much wrong
7599    lol little anthony drew attention himselfmight...
7600                            bumper sticker free tommy
Name: no_stopword, Length: 7601, dtype: object

In [101]:
#from sklearn.feature_extraction.text import TfidfVectorizer
#tfidf = TfidfVectorizer(ngram_range=(1,1), stop_words = 'english', min_df = 0)
#tfidf.fit_transform(df['no_stopword'])

<7601x14254 sparse matrix of type '<class 'numpy.float64'>'
	with 56115 stored elements in Compressed Sparse Row format>

In [107]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = CountVectorizer(min_df=0.05, max_df=0.95,)
X = vectorizer.fit_transform(df['no_stopword']).toarray()

In [108]:
X

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [110]:
from tkinter import YView
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfconverter = TfidfVectorizer(min_df=0.05, max_df=0.95)
Y = tfidfconverter.fit_transform(df['no_stopword']).toarray()

In [112]:
Y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [113]:
from sklearn.cluster import KMeans
import numpy as np

In [118]:
km=KMeans(n_clusters=3, random_state=0)
km.fit(X)
y_cluster=km.predict(X)
y_cluster

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [119]:
#Count Cluster
from collections import Counter
cnt=Counter(y_cluster)
cnt

Counter({0: 7178, 2: 417, 1: 6})